spring.application.name=katalog-gier
spring.datasource.url=jdbc:mysql://localhost:3306/katalog_gier
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false